name: Platform Tests & Build
on: [push]

jobs:
  platform_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set Version
      run: make set-version

    - uses: WillAbides/setup-go-faster@v1.7.0
      env:
        FILELIST_URL: ${{ vars.FILELIST_URL }}
      with:
        go-version: '1.20'

    - name: Build binary
      run: |
        make build-windows

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.VERSION }}.${{ github.run_number }}"
        prerelease: false
        title: "${{ env.VERSION }}.${{ github.run_number }}"
        files: |
          bin/quail-gui.exe
