name: Platform Tests & Build
on: [push]
jobs:
  platform_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set Version
      run: make set-version      
    - name: Setup environment
      shell: bash
      run: |
        echo "::set-env name=GOPATH::${{ github.workspace }}/go"
        echo "::add-path::${{ github.workspace }}/go/bin"
    - name: Build binary
      run: |
        make build-windows
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.VERSION }}.${{ github.run_number }}"
        prerelease: false
        title: "${{ env.VERSION }}.${{ github.run_number }}"
        files: |
          bin/quail-gui.exe
          bin/quail-gui-hash.txt
